version: "2.1"

services:
  postgres:
    container_name: postgres
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 5s
      retries: 5
    image: postgres:9.6
    environment:
      POSTGRES_DB: tola_activity
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always
  elasticsearch:
    container_name: elasticsearch
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9200"]
      interval: 3s
      timeout: 5s
      retries: 5
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0-alpha2
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: web
    image: web
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - elasticsearch
    environment:
      - DJANGO_SETTINGS_MODULE=tola.settings.dev
      - TOLA_DEBUG=True
      - TOLA_ERROR_LOG=error.log
      - TOLA_HOSTNAME=127.0.0.1,localhost
      - TOLA_DB_ENGINE=django.db.backends.postgresql_psycopg2
      - TOLA_DB_NAME=tola_activity
      - TOLA_DB_USER=root
      - TOLA_DB_PASS=root
      - TOLA_DB_HOST=postgres
      - TOLA_DB_PORT=5432
      - ELASTICSEARCH_URL=http://elasticsearch:9200/
      - SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=445847194486-gl2v6ud6ll65vf06vbjaslqqgejad61k.apps.googleusercontent.com
      - SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=qAAdNMQy77Vwqgj4YgOu20f7
      - SOCIAL_AUTH_LOGIN_REDIRECT_URL=http://dev-v2.tolaactivity.app.tola.io/
      - SOCIAL_AUTH_MICROSOFT_GRAPH_KEY=63783b55-0c15-4e94-8ceb-4de040fea71d
      - SOCIAL_AUTH_MICROSOFT_GRAPH_SECRET=w8zgk5dz5JVErCNzc8Jz7EM
      - SOCIAL_AUTH_MICROSOFT_GRAPH_REDIRECT_URL=https://localhost:8000/complete/microsoft-graph
