mysqldb:
  image: mysql:5.7
  restart: always
  env_file: ./config/mysql.env.secret
nginx:
   image: nginx
   restart: always
   volumes:
      - .:/home/TolaActivity
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
   ports:
      - "80:80"
   links:
      - tola
tola:
   build: .
   command: bash -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
   restart: always
   volumes:
       - .:/code
   expose:
       - "8000"
   links:
       - mysqldb
