ADMINS:
 -
   - "admin"
   - "toladata@example.org"

ALLOWED_HOSTS:
 - "127.0.0.1"
 - "localhost"
 - "www.example.org"
 - "www.google.com"
 - "*.github.com"
 - "www.github.com"
 - "api.github.com"
 - "tola-activity-dev.example.org"
 - "tola-activity-demo.example.org"
 - "tola-activity.example.org"
 - "tola-tables.example.org"

EMAIL_USE_TLS: True
EMAIL_HOST: 'smtp.gmail.com'
EMAIL_PORT: 587
EMAIL_HOST_USER: 'sys@example.org'
EMAIL_HOST_PASSWORD: 'XXXXXXXXXXXX'
DEFAULT_FROM_EMAIL: 'sys@example.org'
SERVER_EMAIL: "tola@example.org"
EMAIL_BACKEND: "django.core.mail.backends.filebased.EmailBackend"
EMAIL_FILE_PATH: "/tmp/tola-messages"

DEV_APPS:
 - 'debug_toolbar'

DATABASES:
 default:
   ENGINE: "django.db.backends.mysql"
   NAME: "DB_NAME"
   USER: "DB_USER"
   PASSWORD: "DB_PASSWORD"
   OPTIONS: {"init_command": "SET default_storage_engine=MYISAM",}
   HOST: "localhost"
   PORT: ""

GOOGLE_STEP2_URI: "http://tola.example.org/gwelcome"
GOOGLE_CLIENT_ID: "111111111111.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET: "99999D33DDDDD88777777777"


########## GOOGLE AUTH
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: "111111111111-aaaAAAAABBBBDDEE888SSSCCCCDDDDD9.apps.googleusercontent.com"
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: "XXXXXXXXXXXXXXXXXXXXXXXX"
SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS: "example.org"

TOLA_TABLES_USER: "USER_ACCOUNT_IN_TOLA_TABLES"
TOLA_TABLES_TOKEN: "XXXXXXXXXXXXXXXXXXXXXXXX"


CACHES:
 default:
   BACKEND: "django.core.cache.backends.locmem.LocMemCache"

AUTHENTICATION_BACKENDS:
 # - 'social.backends.google.GoogleOAuth2'
 - 'social_core.backends.google.GoogleOAuth2'
 - 'django.contrib.auth.backends.ModelBackend'

# If report server then limit navigation and allow access to public dashboards
REPORT_SERVER: False
OFFLINE_MODE: False
NON_LDAP: True

TEMPLATE_DEBUG: False
DEBUG: True

EMAIL_HOST_PASSWORD: 'XXXXXXXXXXXX'

# Google Analytics Tracking code
GOOGLE_ANALYTICS_PROPERTY_ID: 'UA-1111111-11'
GOOGLE_ANALYTICS_DOMAIN: 'example.org'


